# Generated by Django 6.0.1 on 2026-02-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scenario_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('scenario_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('loading', 'Loading'), ('resetting', 'Resetting')], default='inactive', max_length=20)),
            ],
            options={
                'verbose_name': 'Scenario',
            },
        ),
    ]
