# Generated by Django 6.0.1 on 2026-03-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariomodel',
            options={'verbose_name': 'Scenario', 'verbose_name_plural': 'Scenarios'},
        ),
    ]
