# Generated by Django 6.0.1 on 2026-03-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_question_answerchoice_quiz_question_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_credentials', models.FileField(blank=True, upload_to='scenario_credentials/')),
            ],
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='scenario_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenariocredentials'),
        ),
    ]
