# Generated by Django 6.0.1 on 2026-03-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenariocredentials_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScenarioCredentials',
            new_name='ScenarioCredential',
        ),
    ]
