# Generated by Django 6.0.1 on 2026-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0005_rename_scenariocredentials_scenariocredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='requires_higher_tier',
            field=models.BooleanField(default=False),
        ),
    ]
